version: '3'

services:
  app:
    build:
      context: node
    image: rafaelps1/node-app
    container_name: app
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
